In [1]:
import torch
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# window
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') # 내 장치가 GPU 인지 CPU 인지 확인

# mac
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu') # 내 장치가 GPU 인지 CPU 인지 확인

print(f"지금 실행중인 하드웨어 장치 : {device}")

model = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS', device=device)

/Users/kimjaeyong/Documents/study/toy_projects/codeit/myvenv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/kimjaeyong/Documents/study/toy_projects/codeit/myvenv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


지금 실행중인 하드웨어 장치 : mps


In [2]:
sentences =[
    '코드잇 강의 좋아요',
    '코드잇 학생들 좋아요',
    '코드잇 강의는 정말 좋아요',
	'코드잇 강의는 정말 재미있어요',
    '삼성동에서 공부하고 있습니다.'
	'삼성동에서 근무하고 있습니다.',
    '오늘 날씨가 좋습니다.',
]

# 문장 임베딩
embeddings = model.encode(sentences, device=device)
print(embeddings.shape)

(6, 768)


In [3]:
print(type(embeddings))

<class 'numpy.ndarray'>


In [5]:
sim = cosine_similarity(
    [embeddings[0]],
    [embeddings[4]],
)

print(sim)

sim_matrix = cosine_similarity(embeddings,embeddings)
print(sim_matrix)

[[0.161403]]
[[1.0000001  0.71295434 0.91886854 0.83026135 0.16140299 0.3438565 ]
 [0.71295434 0.9999998  0.7195976  0.6114042  0.12963414 0.41728717]
 [0.91886854 0.7195976  0.9999999  0.93531    0.18543841 0.450109  ]
 [0.83026135 0.6114042  0.93531    1.0000002  0.18890287 0.39236322]
 [0.16140299 0.12963414 0.18543841 0.18890287 1.         0.10391874]
 [0.3438565  0.41728717 0.450109   0.39236322 0.10391874 0.9999999 ]]


In [7]:
tokenized_sentences = [doc.split() for doc in sentences]
print(tokenized_sentences)

[['코드잇', '강의', '좋아요'], ['코드잇', '학생들', '좋아요'], ['코드잇', '강의는', '정말', '좋아요'], ['코드잇', '강의는', '정말', '재미있어요'], ['삼성동에서', '공부하고', '있습니다.삼성동에서', '근무하고', '있습니다.'], ['오늘', '날씨가', '좋습니다.']]


ModuleNotFoundError: No module named 'gensim'