In [1]:
import torch

In [2]:
data_list = [1,2,3]

tensor = torch.tensor(data_list)

In [3]:
print(type(tensor))

print(tensor)

<class 'torch.Tensor'>
tensor([1, 2, 3])


In [4]:
print(f'data type: {tensor.dtype}')
print(f'number of dimensions: {tensor.ndim}')
print(f'shape: {tensor.shape}')
print(f'device: {tensor.device}')
print(f'requires_grad: {tensor.requires_grad}')

data type: torch.int64
number of dimensions: 1
shape: torch.Size([3])
device: cpu
requires_grad: False


In [5]:
print(f'size: {tensor.size()}')

size: torch.Size([3])


In [8]:
import numpy as np

data_np = np.array([[1,2,3],[4,5,6]])
print(data_np)

tensor_np = torch.tensor(data_np)
print(tensor_np)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
tensor_from_np = torch.from_numpy(data_np)
print(tensor_from_np)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
tensor_as_tensor = torch.as_tensor(data_np)
print(tensor_as_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
data_np[0, 0] = -1

print(f'torch.tensor() result\n{tensor_np}\n')
print(f'torch.from_numpy() result\n{tensor_from_np}\n')
print(f'torch.as_tensor() result\n{tensor_as_tensor}\n')

torch.tensor() result
tensor([[1, 2, 3],
        [4, 5, 6]])

torch.from_numpy() result
tensor([[-1,  2,  3],
        [ 4,  5,  6]])

torch.as_tensor() result
tensor([[-1,  2,  3],
        [ 4,  5,  6]])



In [ ]:
torch_as_tensor2 = torch.from_numpy([[1, 2, 3], [4, 5, 6]]) # call by reference
print(torch_as_tensor2)

TypeError: expected np.ndarray (got list)

In [ ]:
torch_as_tensor2 = torch.as_tensor([[1, 2, 3], [4, 5, 6]]) # call by value
print(torch_as_tensor2)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
print(tensor.dtype)
print(tensor_np.dtype)
print(tensor_from_np.dtype)

torch.int64
torch.int64
torch.int64


In [17]:
gpu_tensor = torch.tensor([1, 2, 3], device='mps')
print(gpu_tensor)

tensor([1, 2, 3], device='mps:0')


In [19]:
print(torch.randn(2, 3))  # Random tensor with shape (2, 3)
print(torch.randn(2, 3, device='mps'))  # Random tensor with shape (2, 3) on GPU
print(torch.randn(2, 3, dtype=torch.float32))  # Random tensor with shape (2, 3) and float32 type
print(torch.randn(2, 3, dtype=torch.float32, device='mps'))  # Random tensor with shape (2, 3), float32 type on GPU

tensor([[-1.7680, -0.1913,  1.3199],
        [ 0.5889,  1.2801,  0.3704]])
tensor([[ 0.3264,  0.2390, -0.7926],
        [-1.1257, -0.4737,  0.2456]], device='mps:0')
tensor([[ 0.0365,  1.3243, -1.6031],
        [ 0.9364, -1.3994, -0.4926]])
tensor([[-0.3285, -1.5224,  2.3481],
        [-0.8357, -2.3443,  0.9032]], device='mps:0')


In [22]:
min_val, max_val = 0, 10
min_val + (max_val - min_val) * torch.rand(2, 3)

tensor([[6.2598, 5.0397, 9.5922],
        [9.8051, 1.2733, 8.8206]])

In [25]:
mu, sigma = 1, 10
mu + sigma * torch.randn(2, 3)

tensor([[ -7.0732,   0.7229,  19.1884],
        [  6.6672,   7.1621, -16.9839]])

In [27]:
print(torch.zeros(2, 3))  # Tensor filled with zeros
print(torch.ones(2, 3))  # Tensor filled with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
print(torch.ones(2,3) * 5)
print(torch.full((2, 3), 5))  # Tensor filled with a specific value

tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[5, 5, 5],
        [5, 5, 5]])


In [30]:
one_sample = torch.ones(2,3) * 5
full_sample = torch.full((2, 3), 5.0)
print(one_sample.dtype)
print(full_sample.dtype)

torch.float32
torch.float32


In [ ]:
data_list = [[1,1], [-1,-1]]
data_np = np.array([[3,4],[5,6]])

tensor_from_list = torch.tensor(data_list)
tensor_from_np_array = torch.tensor(data_np)

print(tensor_from_list)
print(tensor_from_np_array)

tensor([[ 1,  1],
        [-1, -1]])
tensor([[3, 4],
        [5, 6]])


In [32]:
tensor = torch.ones(2,2)

np_arr = tensor.numpy()
print(tensor.dtype)
print(type(np_arr))

torch.float32
<class 'numpy.ndarray'>


In [40]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

In [34]:
a+b

tensor([[ 6,  8],
        [10, 12]])

In [35]:
torch.add(a, b)

tensor([[ 6,  8],
        [10, 12]])

In [36]:
a * b

tensor([[ 5, 12],
        [21, 32]])

In [37]:
torch.multiply(a, b)

tensor([[ 5, 12],
        [21, 32]])

In [38]:
torch.matmul(a, b)  # Matrix multiplication

tensor([[19, 22],
        [43, 50]])

In [43]:
a = torch.tensor(
    [
        [1,2],
        [3,4],
		[5,6],
        [7,8]
	]
)

b = torch.tensor(
    [
        [1,0,0],
        [0,0,1],
	]
)

In [44]:
torch.matmul(a, b)  # Matrix multiplication

tensor([[1, 0, 2],
        [3, 0, 4],
        [5, 0, 6],
        [7, 0, 8]])

In [45]:
a @ b

tensor([[1, 0, 2],
        [3, 0, 4],
        [5, 0, 6],
        [7, 0, 8]])

- 실습 설명

세 개의 텐서 tensor0, tensor1, tensor2가 주어져 있습니다. 다음 단계를 따라 코드를 작성해 주세요.

1. tensor0과 tensor1을 더합니다.
2. 1번 결과와 tensor2를 행렬곱합니다.
3. 2번 결과에서 첫 번째 열에는 2를 더하고, 두 번째 열에서는 2를 뺍니다.
4. 3번 결과를 NumPy array로 변환합니다. 이때 변수 이름은 final_np_array로 설정합니다.

실습 결과

코드 마지막 부분에서 print() 함수로 출력한 결과가 아래처럼 나와야 합니다.

```
[[6 -6]
[0 0]]
```

In [56]:
tensor0 = torch.tensor(
    [
        [1,1],
        [-1, -1]
	]
)

tensor1 = torch.tensor(
    [
        [1,1],
        [0,0]
	]
)

tensor2 = torch.tensor(
    [
        [1,-1],
        [1,-1]
	]
)

final_np_array = (((tensor0 + tensor1) @ tensor2) + torch.tensor([2,-2])).numpy()
print(final_np_array)
print(type(final_np_array))




[[ 6 -6]
 [ 0  0]]
<class 'numpy.ndarray'>


In [57]:
x = torch.randn(2,3,4)
permuted = x.permute(2, 0, 1)  # Change the order of dimensions
print(permuted.size())

torch.Size([4, 2, 3])


In [59]:
print(x)
print(permuted)

tensor([[[ 0.8168, -0.7544, -1.6806,  0.1625],
         [ 0.3338, -1.2003,  0.8216, -1.6143],
         [-0.2981, -1.4509,  1.6540,  0.3604]],

        [[ 0.8285, -0.1001, -0.1716,  2.2248],
         [ 0.5789, -0.4503,  0.1843,  1.6029],
         [-2.2948,  1.4153, -0.3670,  0.6782]]])
tensor([[[ 0.8168,  0.3338, -0.2981],
         [ 0.8285,  0.5789, -2.2948]],

        [[-0.7544, -1.2003, -1.4509],
         [-0.1001, -0.4503,  1.4153]],

        [[-1.6806,  0.8216,  1.6540],
         [-0.1716,  0.1843, -0.3670]],

        [[ 0.1625, -1.6143,  0.3604],
         [ 2.2248,  1.6029,  0.6782]]])


In [60]:
x1 = torch.randn(2, 3)
x2 = x1.T

print(x1)
print(x2)

tensor([[-0.9025,  0.1493, -0.3046],
        [-0.7238, -0.3083, -1.7261]])
tensor([[-0.9025, -0.7238],
        [ 0.1493, -0.3083],
        [-0.3046, -1.7261]])


In [62]:
x = torch.randn(1,4,3)
print(x)
x = x.squeeze()
print(x)

tensor([[[ 0.4290,  0.4886, -0.0110],
         [ 0.2603, -0.0799,  0.0978],
         [ 2.1691, -0.1703,  1.1170],
         [-0.6673,  0.1638, -0.1148]]])
tensor([[ 0.4290,  0.4886, -0.0110],
        [ 0.2603, -0.0799,  0.0978],
        [ 2.1691, -0.1703,  1.1170],
        [-0.6673,  0.1638, -0.1148]])


In [68]:
x = torch.randn(1,28,1,28)
print(x.size())
x = x.squeeze(0)
print(x.size())
x = x.squeeze(1)
print(x.size())

torch.Size([1, 28, 1, 28])
torch.Size([28, 1, 28])
torch.Size([28, 28])


In [ ]:
x = torch.randn(28,28)
x = x.unsqueeze(-1)  # Add a new dimension
print(x.size())

torch.Size([28, 28, 1])


In [72]:
x = torch.randn(3,4)
res = x.view(2,6)

print(res.size())

torch.Size([2, 6])


In [74]:
x.is_contiguous()

True

In [77]:
x = torch.ones(3,16,28)
x_permued = x.permute(2,1,0)
x_sliced = x[:,:,:10]

print(x_permued.is_contiguous())
print(x_sliced.is_contiguous())

False
False


In [ ]:
xx = x_permued.contiguous()
print(x_permued.is_contiguous())
print(xx.is_contiguous())

xx.view(16,3,28)
x_permued.view(16,3,28)  # This will raise an error if x_permued is not contiguous

False
True


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
x = torch.ones(10,3,4,5)
print(x.size())
print(torch.transpose(x,1,2).size()) # 사이즈 교환

torch.Size([10, 3, 4, 5])
torch.Size([10, 4, 3, 5])


In [ ]:
x = torch.ones(2,3,4)

# h, w, c -> c, h, w  pytorch = chw, opencv = hwc 
# height, width, channels -> channels, height, width
permuted = x.permute(2, 0, 1)

In [ ]:
x = torch.zeros(2,3)
y = torch.ones(2,3)

# concatenate
cat0 = torch.cat([x,y], dim=0)  # Concatenate along the first dimension
cat1 = torch.cat([x,y], dim=1)  # Concatenate along the second dimension

print(x)
print(y)

print(cat0)
print(cat1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])


In [87]:
st0 = torch.stack([x,y], dim=0)  # Stack along a new dimension
st1 = torch.stack([x,y], dim=1)  # Stack along a new dimension

print(x)
print(y)

print(st0)
print(st1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0., 0., 0.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [1., 1., 1.]]])


In [88]:
print(cat0.size())
print(cat1.size())
print(st0.size())
print(st1.size())

torch.Size([4, 3])
torch.Size([2, 6])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
